// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/bundleexchange.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Checkpoint is a verifiable point in the canonical history.
type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hlc           *HLCTimestamp          `protobuf:"bytes,1,opt,name=hlc,proto3" json:"hlc,omitempty"`
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_proto_bundleexchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bundleexchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_proto_bundleexchange_proto_rawDescGZIP(), []int{0}
}

func (x *Checkpoint) GetHlc() *HLCTimestamp {
	if x != nil {
		return x.Hlc
	}
	return nil
}

func (x *Checkpoint) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

type BundleRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaxCommits         int32                  `protobuf:"varint,1,opt,name=max_commits,json=maxCommits,proto3" json:"max_commits,omitempty"`
	MaxBytes           int64                  `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	AllowPartial       bool                   `protobuf:"varint,3,opt,name=allow_partial,json=allowPartial,proto3" json:"allow_partial,omitempty"`
	IncludeDiagnostics bool                   `protobuf:"varint,4,opt,name=include_diagnostics,json=includeDiagnostics,proto3" json:"include_diagnostics,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BundleRequest) Reset() {
	*x = BundleRequest{}
	mi := &file_proto_bundleexchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleRequest) ProtoMessage() {}

func (x *BundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bundleexchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleRequest.ProtoReflect.Descriptor instead.
func (*BundleRequest) Descriptor() ([]byte, []int) {
	return file_proto_bundleexchange_proto_rawDescGZIP(), []int{1}
}

func (x *BundleRequest) GetMaxCommits() int32 {
	if x != nil {
		return x.MaxCommits
	}
	return 0
}

func (x *BundleRequest) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *BundleRequest) GetAllowPartial() bool {
	if x != nil {
		return x.AllowPartial
	}
	return false
}

func (x *BundleRequest) GetIncludeDiagnostics() bool {
	if x != nil {
		return x.IncludeDiagnostics
	}
	return false
}

type BundleHeader struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Base                *Checkpoint            `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ProviderHeadHlc     *HLCTimestamp          `protobuf:"bytes,2,opt,name=provider_head_hlc,json=providerHeadHlc,proto3" json:"provider_head_hlc,omitempty"`
	ProviderHeadHash    string                 `protobuf:"bytes,3,opt,name=provider_head_hash,json=providerHeadHash,proto3" json:"provider_head_hash,omitempty"`
	BaseMismatch        bool                   `protobuf:"varint,4,opt,name=base_mismatch,json=baseMismatch,proto3" json:"base_mismatch,omitempty"`
	ProviderCheckpoints []*Checkpoint          `protobuf:"bytes,5,rep,name=provider_checkpoints,json=providerCheckpoints,proto3" json:"provider_checkpoints,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BundleHeader) Reset() {
	*x = BundleHeader{}
	mi := &file_proto_bundleexchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleHeader) ProtoMessage() {}

func (x *BundleHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bundleexchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleHeader.ProtoReflect.Descriptor instead.
func (*BundleHeader) Descriptor() ([]byte, []int) {
	return file_proto_bundleexchange_proto_rawDescGZIP(), []int{2}
}

func (x *BundleHeader) GetBase() *Checkpoint {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *BundleHeader) GetProviderHeadHlc() *HLCTimestamp {
	if x != nil {
		return x.ProviderHeadHlc
	}
	return nil
}

func (x *BundleHeader) GetProviderHeadHash() string {
	if x != nil {
		return x.ProviderHeadHash
	}
	return ""
}

func (x *BundleHeader) GetBaseMismatch() bool {
	if x != nil {
		return x.BaseMismatch
	}
	return false
}

func (x *BundleHeader) GetProviderCheckpoints() []*Checkpoint {
	if x != nil {
		return x.ProviderCheckpoints
	}
	return nil
}

type BundledCommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hlc           *HLCTimestamp          `protobuf:"bytes,1,opt,name=hlc,proto3" json:"hlc,omitempty"`
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	MetadataSig   []byte                 `protobuf:"bytes,4,opt,name=metadata_sig,json=metadataSig,proto3" json:"metadata_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundledCommit) Reset() {
	*x = BundledCommit{}
	mi := &file_proto_bundleexchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundledCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundledCommit) ProtoMessage() {}

func (x *BundledCommit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bundleexchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundledCommit.ProtoReflect.Descriptor instead.
func (*BundledCommit) Descriptor() ([]byte, []int) {
	return file_proto_bundleexchange_proto_rawDescGZIP(), []int{3}
}

func (x *BundledCommit) GetHlc() *HLCTimestamp {
	if x != nil {
		return x.Hlc
	}
	return nil
}

func (x *BundledCommit) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *BundledCommit) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

func (x *BundledCommit) GetMetadataSig() []byte {
	if x != nil {
		return x.MetadataSig
	}
	return nil
}

type BundledChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Codec         uint32                 `protobuf:"varint,3,opt,name=codec,proto3" json:"codec,omitempty"` // 0=raw, 1=nbs-compressed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundledChunk) Reset() {
	*x = BundledChunk{}
	mi := &file_proto_bundleexchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundledChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundledChunk) ProtoMessage() {}

func (x *BundledChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bundleexchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundledChunk.ProtoReflect.Descriptor instead.
func (*BundledChunk) Descriptor() ([]byte, []int) {
	return file_proto_bundleexchange_proto_rawDescGZIP(), []int{4}
}

func (x *BundledChunk) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BundledChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BundledChunk) GetCodec() uint32 {
	if x != nil {
		return x.Codec
	}
	return 0
}

type GetBundleSinceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bundle is returned for commits strictly after base.hlc.
	Base          *Checkpoint    `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Req           *BundleRequest `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBundleSinceRequest) Reset() {
	*x = GetBundleSinceRequest{}
	mi := &file_proto_bundleexchange_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBundleSinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBundleSinceRequest) ProtoMessage() {}

func (x *GetBundleSinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bundleexchange_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBundleSinceRequest.ProtoReflect.Descriptor instead.
func (*GetBundleSinceRequest) Descriptor() ([]byte, []int) {
	return file_proto_bundleexchange_proto_rawDescGZIP(), []int{5}
}

func (x *GetBundleSinceRequest) GetBase() *Checkpoint {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetBundleSinceRequest) GetReq() *BundleRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

type GetBundleSinceChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*GetBundleSinceChunk_Header
	//	*GetBundleSinceChunk_Commit
	//	*GetBundleSinceChunk_Chunk
	Item          isGetBundleSinceChunk_Item `protobuf_oneof:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBundleSinceChunk) Reset() {
	*x = GetBundleSinceChunk{}
	mi := &file_proto_bundleexchange_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBundleSinceChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBundleSinceChunk) ProtoMessage() {}

func (x *GetBundleSinceChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bundleexchange_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBundleSinceChunk.ProtoReflect.Descriptor instead.
func (*GetBundleSinceChunk) Descriptor() ([]byte, []int) {
	return file_proto_bundleexchange_proto_rawDescGZIP(), []int{6}
}

func (x *GetBundleSinceChunk) GetItem() isGetBundleSinceChunk_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetBundleSinceChunk) GetHeader() *BundleHeader {
	if x != nil {
		if x, ok := x.Item.(*GetBundleSinceChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *GetBundleSinceChunk) GetCommit() *BundledCommit {
	if x != nil {
		if x, ok := x.Item.(*GetBundleSinceChunk_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *GetBundleSinceChunk) GetChunk() *BundledChunk {
	if x != nil {
		if x, ok := x.Item.(*GetBundleSinceChunk_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isGetBundleSinceChunk_Item interface {
	isGetBundleSinceChunk_Item()
}

type GetBundleSinceChunk_Header struct {
	Header *BundleHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type GetBundleSinceChunk_Commit struct {
	Commit *BundledCommit `protobuf:"bytes,2,opt,name=commit,proto3,oneof"`
}

type GetBundleSinceChunk_Chunk struct {
	Chunk *BundledChunk `protobuf:"bytes,3,opt,name=chunk,proto3,oneof"`
}

func (*GetBundleSinceChunk_Header) isGetBundleSinceChunk_Item() {}

func (*GetBundleSinceChunk_Commit) isGetBundleSinceChunk_Item() {}

func (*GetBundleSinceChunk_Chunk) isGetBundleSinceChunk_Item() {}

var File_proto_bundleexchange_proto protoreflect.FileDescriptor

const file_proto_bundleexchange_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/bundleexchange.proto\x12\x05proto\x1a\x14proto/dbsyncer.proto\"T\n" +
	"\n" +
	"Checkpoint\x12%\n" +
	"\x03hlc\x18\x01 \x01(\v2\x13.proto.HLCTimestampR\x03hlc\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\"\xa3\x01\n" +
	"\rBundleRequest\x12\x1f\n" +
	"\vmax_commits\x18\x01 \x01(\x05R\n" +
	"maxCommits\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\x03R\bmaxBytes\x12#\n" +
	"\rallow_partial\x18\x03 \x01(\bR\fallowPartial\x12/\n" +
	"\x13include_diagnostics\x18\x04 \x01(\bR\x12includeDiagnostics\"\x8f\x02\n" +
	"\fBundleHeader\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.proto.CheckpointR\x04base\x12?\n" +
	"\x11provider_head_hlc\x18\x02 \x01(\v2\x13.proto.HLCTimestampR\x0fproviderHeadHlc\x12,\n" +
	"\x12provider_head_hash\x18\x03 \x01(\tR\x10providerHeadHash\x12#\n" +
	"\rbase_mismatch\x18\x04 \x01(\bR\fbaseMismatch\x12D\n" +
	"\x14provider_checkpoints\x18\x05 \x03(\v2\x11.proto.CheckpointR\x13providerCheckpoints\"\x9f\x01\n" +
	"\rBundledCommit\x12%\n" +
	"\x03hlc\x18\x01 \x01(\v2\x13.proto.HLCTimestampR\x03hlc\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\fR\fmetadataJson\x12!\n" +
	"\fmetadata_sig\x18\x04 \x01(\fR\vmetadataSig\"L\n" +
	"\fBundledChunk\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05codec\x18\x03 \x01(\rR\x05codec\"f\n" +
	"\x15GetBundleSinceRequest\x12%\n" +
	"\x04base\x18\x01 \x01(\v2\x11.proto.CheckpointR\x04base\x12&\n" +
	"\x03req\x18\x02 \x01(\v2\x14.proto.BundleRequestR\x03req\"\xa9\x01\n" +
	"\x13GetBundleSinceChunk\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x13.proto.BundleHeaderH\x00R\x06header\x12.\n" +
	"\x06commit\x18\x02 \x01(\v2\x14.proto.BundledCommitH\x00R\x06commit\x12+\n" +
	"\x05chunk\x18\x03 \x01(\v2\x13.proto.BundledChunkH\x00R\x05chunkB\x06\n" +
	"\x04item2^\n" +
	"\x0eBundleExchange\x12L\n" +
	"\x0eGetBundleSince\x12\x1c.proto.GetBundleSinceRequest\x1a\x1a.proto.GetBundleSinceChunk0\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_bundleexchange_proto_rawDescOnce sync.Once
	file_proto_bundleexchange_proto_rawDescData []byte
)

func file_proto_bundleexchange_proto_rawDescGZIP() []byte {
	file_proto_bundleexchange_proto_rawDescOnce.Do(func() {
		file_proto_bundleexchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bundleexchange_proto_rawDesc), len(file_proto_bundleexchange_proto_rawDesc)))
	})
	return file_proto_bundleexchange_proto_rawDescData
}

var file_proto_bundleexchange_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_bundleexchange_proto_goTypes = []any{
	(*Checkpoint)(nil),            // 0: proto.Checkpoint
	(*BundleRequest)(nil),         // 1: proto.BundleRequest
	(*BundleHeader)(nil),          // 2: proto.BundleHeader
	(*BundledCommit)(nil),         // 3: proto.BundledCommit
	(*BundledChunk)(nil),          // 4: proto.BundledChunk
	(*GetBundleSinceRequest)(nil), // 5: proto.GetBundleSinceRequest
	(*GetBundleSinceChunk)(nil),   // 6: proto.GetBundleSinceChunk
	(*HLCTimestamp)(nil),          // 7: proto.HLCTimestamp
}
var file_proto_bundleexchange_proto_depIdxs = []int32{
	7,  // 0: proto.Checkpoint.hlc:type_name -> proto.HLCTimestamp
	0,  // 1: proto.BundleHeader.base:type_name -> proto.Checkpoint
	7,  // 2: proto.BundleHeader.provider_head_hlc:type_name -> proto.HLCTimestamp
	0,  // 3: proto.BundleHeader.provider_checkpoints:type_name -> proto.Checkpoint
	7,  // 4: proto.BundledCommit.hlc:type_name -> proto.HLCTimestamp
	0,  // 5: proto.GetBundleSinceRequest.base:type_name -> proto.Checkpoint
	1,  // 6: proto.GetBundleSinceRequest.req:type_name -> proto.BundleRequest
	2,  // 7: proto.GetBundleSinceChunk.header:type_name -> proto.BundleHeader
	3,  // 8: proto.GetBundleSinceChunk.commit:type_name -> proto.BundledCommit
	4,  // 9: proto.GetBundleSinceChunk.chunk:type_name -> proto.BundledChunk
	5,  // 10: proto.BundleExchange.GetBundleSince:input_type -> proto.GetBundleSinceRequest
	6,  // 11: proto.BundleExchange.GetBundleSince:output_type -> proto.GetBundleSinceChunk
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_bundleexchange_proto_init() }
func file_proto_bundleexchange_proto_init() {
	if File_proto_bundleexchange_proto != nil {
		return
	}
	file_proto_dbsyncer_proto_init()
	file_proto_bundleexchange_proto_msgTypes[6].OneofWrappers = []any{
		(*GetBundleSinceChunk_Header)(nil),
		(*GetBundleSinceChunk_Commit)(nil),
		(*GetBundleSinceChunk_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bundleexchange_proto_rawDesc), len(file_proto_bundleexchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bundleexchange_proto_goTypes,
		DependencyIndexes: file_proto_bundleexchange_proto_depIdxs,
		MessageInfos:      file_proto_bundleexchange_proto_msgTypes,
	}.Build()
	File_proto_bundleexchange_proto = out.File
	file_proto_bundleexchange_proto_goTypes = nil
	file_proto_bundleexchange_proto_depIdxs = nil
}
