// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/bundleexchange.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BundleExchange_GetBundleSince_FullMethodName = "/proto.BundleExchange/GetBundleSince"
)

// BundleExchangeClient is the client API for BundleExchange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BundleExchangeClient interface {
	GetBundleSince(ctx context.Context, in *GetBundleSinceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBundleSinceChunk], error)
}

type bundleExchangeClient struct {
	cc grpc.ClientConnInterface
}

func NewBundleExchangeClient(cc grpc.ClientConnInterface) BundleExchangeClient {
	return &bundleExchangeClient{cc}
}

func (c *bundleExchangeClient) GetBundleSince(ctx context.Context, in *GetBundleSinceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBundleSinceChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BundleExchange_ServiceDesc.Streams[0], BundleExchange_GetBundleSince_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBundleSinceRequest, GetBundleSinceChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BundleExchange_GetBundleSinceClient = grpc.ServerStreamingClient[GetBundleSinceChunk]

// BundleExchangeServer is the server API for BundleExchange service.
// All implementations must embed UnimplementedBundleExchangeServer
// for forward compatibility.
type BundleExchangeServer interface {
	GetBundleSince(*GetBundleSinceRequest, grpc.ServerStreamingServer[GetBundleSinceChunk]) error
	mustEmbedUnimplementedBundleExchangeServer()
}

// UnimplementedBundleExchangeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBundleExchangeServer struct{}

func (UnimplementedBundleExchangeServer) GetBundleSince(*GetBundleSinceRequest, grpc.ServerStreamingServer[GetBundleSinceChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetBundleSince not implemented")
}
func (UnimplementedBundleExchangeServer) mustEmbedUnimplementedBundleExchangeServer() {}
func (UnimplementedBundleExchangeServer) testEmbeddedByValue()                        {}

// UnsafeBundleExchangeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BundleExchangeServer will
// result in compilation errors.
type UnsafeBundleExchangeServer interface {
	mustEmbedUnimplementedBundleExchangeServer()
}

func RegisterBundleExchangeServer(s grpc.ServiceRegistrar, srv BundleExchangeServer) {
	// If the following call pancis, it indicates UnimplementedBundleExchangeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BundleExchange_ServiceDesc, srv)
}

func _BundleExchange_GetBundleSince_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBundleSinceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BundleExchangeServer).GetBundleSince(m, &grpc.GenericServerStream[GetBundleSinceRequest, GetBundleSinceChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BundleExchange_GetBundleSinceServer = grpc.ServerStreamingServer[GetBundleSinceChunk]

// BundleExchange_ServiceDesc is the grpc.ServiceDesc for BundleExchange service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BundleExchange_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BundleExchange",
	HandlerType: (*BundleExchangeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBundleSince",
			Handler:       _BundleExchange_GetBundleSince_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/bundleexchange.proto",
}
