// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/dbdownloader.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_proto_dbdownloader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbdownloader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_dbdownloader_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DownloadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_proto_dbdownloader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbdownloader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_dbdownloader_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadFileResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type DownloadChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []string               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunksRequest) Reset() {
	*x = DownloadChunksRequest{}
	mi := &file_proto_dbdownloader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunksRequest) ProtoMessage() {}

func (x *DownloadChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbdownloader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunksRequest.ProtoReflect.Descriptor instead.
func (*DownloadChunksRequest) Descriptor() ([]byte, []int) {
	return file_proto_dbdownloader_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadChunksRequest) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type DownloadChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunksResponse) Reset() {
	*x = DownloadChunksResponse{}
	mi := &file_proto_dbdownloader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunksResponse) ProtoMessage() {}

func (x *DownloadChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbdownloader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunksResponse.ProtoReflect.Descriptor instead.
func (*DownloadChunksResponse) Descriptor() ([]byte, []int) {
	return file_proto_dbdownloader_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadChunksResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *DownloadChunksResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_proto_dbdownloader_proto protoreflect.FileDescriptor

const file_proto_dbdownloader_proto_rawDesc = "" +
	"\n" +
	"\x18proto/dbdownloader.proto\x12\x05proto\"%\n" +
	"\x13DownloadFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x14DownloadFileResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"/\n" +
	"\x15DownloadChunksRequest\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\tR\x06hashes\"B\n" +
	"\x16DownloadChunksResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk2\xa8\x01\n" +
	"\n" +
	"Downloader\x12I\n" +
	"\fDownloadFile\x12\x1a.proto.DownloadFileRequest\x1a\x1b.proto.DownloadFileResponse0\x01\x12O\n" +
	"\x0eDownloadChunks\x12\x1c.proto.DownloadChunksRequest\x1a\x1d.proto.DownloadChunksResponse0\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_dbdownloader_proto_rawDescOnce sync.Once
	file_proto_dbdownloader_proto_rawDescData []byte
)

func file_proto_dbdownloader_proto_rawDescGZIP() []byte {
	file_proto_dbdownloader_proto_rawDescOnce.Do(func() {
		file_proto_dbdownloader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dbdownloader_proto_rawDesc), len(file_proto_dbdownloader_proto_rawDesc)))
	})
	return file_proto_dbdownloader_proto_rawDescData
}

var file_proto_dbdownloader_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_dbdownloader_proto_goTypes = []any{
	(*DownloadFileRequest)(nil),    // 0: proto.DownloadFileRequest
	(*DownloadFileResponse)(nil),   // 1: proto.DownloadFileResponse
	(*DownloadChunksRequest)(nil),  // 2: proto.DownloadChunksRequest
	(*DownloadChunksResponse)(nil), // 3: proto.DownloadChunksResponse
}
var file_proto_dbdownloader_proto_depIdxs = []int32{
	0, // 0: proto.Downloader.DownloadFile:input_type -> proto.DownloadFileRequest
	2, // 1: proto.Downloader.DownloadChunks:input_type -> proto.DownloadChunksRequest
	1, // 2: proto.Downloader.DownloadFile:output_type -> proto.DownloadFileResponse
	3, // 3: proto.Downloader.DownloadChunks:output_type -> proto.DownloadChunksResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dbdownloader_proto_init() }
func file_proto_dbdownloader_proto_init() {
	if File_proto_dbdownloader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dbdownloader_proto_rawDesc), len(file_proto_dbdownloader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dbdownloader_proto_goTypes,
		DependencyIndexes: file_proto_dbdownloader_proto_depIdxs,
		MessageInfos:      file_proto_dbdownloader_proto_msgTypes,
	}.Build()
	File_proto_dbdownloader_proto = out.File
	file_proto_dbdownloader_proto_goTypes = nil
	file_proto_dbdownloader_proto_depIdxs = nil
}
