// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/gossip.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepoId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	RepoName      string                 `protobuf:"bytes,2,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoId) Reset() {
	*x = RepoId{}
	mi := &file_proto_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoId) ProtoMessage() {}

func (x *RepoId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoId.ProtoReflect.Descriptor instead.
func (*RepoId) Descriptor() ([]byte, []int) {
	return file_proto_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *RepoId) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *RepoId) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

// Checkpoint is a compact prefix summary entry (HLC + commit hash).
type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hlc           *HLCTimestamp          `protobuf:"bytes,1,opt,name=hlc,proto3" json:"hlc,omitempty"`
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_proto_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_proto_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *Checkpoint) GetHlc() *HLCTimestamp {
	if x != nil {
		return x.Hlc
	}
	return nil
}

func (x *Checkpoint) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

// CommitAdV1 is the gossip payload for a commit advertisement.
type CommitAdV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoId                `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Hlc           *HLCTimestamp          `protobuf:"bytes,2,opt,name=hlc,proto3" json:"hlc,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	MetadataSig   []byte                 `protobuf:"bytes,4,opt,name=metadata_sig,json=metadataSig,proto3" json:"metadata_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitAdV1) Reset() {
	*x = CommitAdV1{}
	mi := &file_proto_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitAdV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAdV1) ProtoMessage() {}

func (x *CommitAdV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAdV1.ProtoReflect.Descriptor instead.
func (*CommitAdV1) Descriptor() ([]byte, []int) {
	return file_proto_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *CommitAdV1) GetRepo() *RepoId {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *CommitAdV1) GetHlc() *HLCTimestamp {
	if x != nil {
		return x.Hlc
	}
	return nil
}

func (x *CommitAdV1) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

func (x *CommitAdV1) GetMetadataSig() []byte {
	if x != nil {
		return x.MetadataSig
	}
	return nil
}

// DigestV1 is a compact anti-entropy summary used to negotiate a shared base.
type DigestV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoId                `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	HeadHlc       *HLCTimestamp          `protobuf:"bytes,2,opt,name=head_hlc,json=headHlc,proto3" json:"head_hlc,omitempty"`
	HeadHash      string                 `protobuf:"bytes,3,opt,name=head_hash,json=headHash,proto3" json:"head_hash,omitempty"`
	Checkpoints   []*Checkpoint          `protobuf:"bytes,4,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigestV1) Reset() {
	*x = DigestV1{}
	mi := &file_proto_gossip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestV1) ProtoMessage() {}

func (x *DigestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestV1.ProtoReflect.Descriptor instead.
func (*DigestV1) Descriptor() ([]byte, []int) {
	return file_proto_gossip_proto_rawDescGZIP(), []int{3}
}

func (x *DigestV1) GetRepo() *RepoId {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *DigestV1) GetHeadHlc() *HLCTimestamp {
	if x != nil {
		return x.HeadHlc
	}
	return nil
}

func (x *DigestV1) GetHeadHash() string {
	if x != nil {
		return x.HeadHash
	}
	return ""
}

func (x *DigestV1) GetCheckpoints() []*Checkpoint {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

// GossipMessage is the envelope published on the gossip topic.
type GossipMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GossipMessage_CommitAd
	//	*GossipMessage_Digest
	Msg           isGossipMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_proto_gossip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_proto_gossip_proto_rawDescGZIP(), []int{4}
}

func (x *GossipMessage) GetMsg() isGossipMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GossipMessage) GetCommitAd() *CommitAdV1 {
	if x != nil {
		if x, ok := x.Msg.(*GossipMessage_CommitAd); ok {
			return x.CommitAd
		}
	}
	return nil
}

func (x *GossipMessage) GetDigest() *DigestV1 {
	if x != nil {
		if x, ok := x.Msg.(*GossipMessage_Digest); ok {
			return x.Digest
		}
	}
	return nil
}

type isGossipMessage_Msg interface {
	isGossipMessage_Msg()
}

type GossipMessage_CommitAd struct {
	CommitAd *CommitAdV1 `protobuf:"bytes,1,opt,name=commit_ad,json=commitAd,proto3,oneof"`
}

type GossipMessage_Digest struct {
	Digest *DigestV1 `protobuf:"bytes,2,opt,name=digest,proto3,oneof"`
}

func (*GossipMessage_CommitAd) isGossipMessage_Msg() {}

func (*GossipMessage_Digest) isGossipMessage_Msg() {}

var File_proto_gossip_proto protoreflect.FileDescriptor

const file_proto_gossip_proto_rawDesc = "" +
	"\n" +
	"\x12proto/gossip.proto\x12\x05proto\x1a\x0fproto/hlc.proto\"7\n" +
	"\x06RepoId\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x1b\n" +
	"\trepo_name\x18\x02 \x01(\tR\brepoName\"T\n" +
	"\n" +
	"Checkpoint\x12%\n" +
	"\x03hlc\x18\x01 \x01(\v2\x13.proto.HLCTimestampR\x03hlc\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\"\x9e\x01\n" +
	"\n" +
	"CommitAdV1\x12!\n" +
	"\x04repo\x18\x01 \x01(\v2\r.proto.RepoIdR\x04repo\x12%\n" +
	"\x03hlc\x18\x02 \x01(\v2\x13.proto.HLCTimestampR\x03hlc\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\fR\fmetadataJson\x12!\n" +
	"\fmetadata_sig\x18\x04 \x01(\fR\vmetadataSig\"\xaf\x01\n" +
	"\bDigestV1\x12!\n" +
	"\x04repo\x18\x01 \x01(\v2\r.proto.RepoIdR\x04repo\x12.\n" +
	"\bhead_hlc\x18\x02 \x01(\v2\x13.proto.HLCTimestampR\aheadHlc\x12\x1b\n" +
	"\thead_hash\x18\x03 \x01(\tR\bheadHash\x123\n" +
	"\vcheckpoints\x18\x04 \x03(\v2\x11.proto.CheckpointR\vcheckpoints\"s\n" +
	"\rGossipMessage\x120\n" +
	"\tcommit_ad\x18\x01 \x01(\v2\x11.proto.CommitAdV1H\x00R\bcommitAd\x12)\n" +
	"\x06digest\x18\x02 \x01(\v2\x0f.proto.DigestV1H\x00R\x06digestB\x05\n" +
	"\x03msgB\tZ\a./protob\x06proto3"

var (
	file_proto_gossip_proto_rawDescOnce sync.Once
	file_proto_gossip_proto_rawDescData []byte
)

func file_proto_gossip_proto_rawDescGZIP() []byte {
	file_proto_gossip_proto_rawDescOnce.Do(func() {
		file_proto_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gossip_proto_rawDesc), len(file_proto_gossip_proto_rawDesc)))
	})
	return file_proto_gossip_proto_rawDescData
}

var file_proto_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_gossip_proto_goTypes = []any{
	(*RepoId)(nil),        // 0: proto.RepoId
	(*Checkpoint)(nil),    // 1: proto.Checkpoint
	(*CommitAdV1)(nil),    // 2: proto.CommitAdV1
	(*DigestV1)(nil),      // 3: proto.DigestV1
	(*GossipMessage)(nil), // 4: proto.GossipMessage
	(*HLCTimestamp)(nil),  // 5: proto.HLCTimestamp
}
var file_proto_gossip_proto_depIdxs = []int32{
	5, // 0: proto.Checkpoint.hlc:type_name -> proto.HLCTimestamp
	0, // 1: proto.CommitAdV1.repo:type_name -> proto.RepoId
	5, // 2: proto.CommitAdV1.hlc:type_name -> proto.HLCTimestamp
	0, // 3: proto.DigestV1.repo:type_name -> proto.RepoId
	5, // 4: proto.DigestV1.head_hlc:type_name -> proto.HLCTimestamp
	1, // 5: proto.DigestV1.checkpoints:type_name -> proto.Checkpoint
	2, // 6: proto.GossipMessage.commit_ad:type_name -> proto.CommitAdV1
	3, // 7: proto.GossipMessage.digest:type_name -> proto.DigestV1
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_gossip_proto_init() }
func file_proto_gossip_proto_init() {
	if File_proto_gossip_proto != nil {
		return
	}
	file_proto_hlc_proto_init()
	file_proto_gossip_proto_msgTypes[4].OneofWrappers = []any{
		(*GossipMessage_CommitAd)(nil),
		(*GossipMessage_Digest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gossip_proto_rawDesc), len(file_proto_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_gossip_proto_goTypes,
		DependencyIndexes: file_proto_gossip_proto_depIdxs,
		MessageInfos:      file_proto_gossip_proto_msgTypes,
	}.Build()
	File_proto_gossip_proto = out.File
	file_proto_gossip_proto_goTypes = nil
	file_proto_gossip_proto_depIdxs = nil
}
