// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/gossip.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepoId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	RepoName      string                 `protobuf:"bytes,2,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoId) Reset() {
	*x = RepoId{}
	mi := &file_proto_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoId) ProtoMessage() {}

func (x *RepoId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoId.ProtoReflect.Descriptor instead.
func (*RepoId) Descriptor() ([]byte, []int) {
	return file_proto_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *RepoId) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *RepoId) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

// CommitAdV1 is the gossip payload for a commit advertisement.
type CommitAdV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoId                `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Hlc           *HLCTimestamp          `protobuf:"bytes,2,opt,name=hlc,proto3" json:"hlc,omitempty"`
	MetadataJson  []byte                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	MetadataSig   []byte                 `protobuf:"bytes,4,opt,name=metadata_sig,json=metadataSig,proto3" json:"metadata_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitAdV1) Reset() {
	*x = CommitAdV1{}
	mi := &file_proto_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitAdV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAdV1) ProtoMessage() {}

func (x *CommitAdV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAdV1.ProtoReflect.Descriptor instead.
func (*CommitAdV1) Descriptor() ([]byte, []int) {
	return file_proto_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *CommitAdV1) GetRepo() *RepoId {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *CommitAdV1) GetHlc() *HLCTimestamp {
	if x != nil {
		return x.Hlc
	}
	return nil
}

func (x *CommitAdV1) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

func (x *CommitAdV1) GetMetadataSig() []byte {
	if x != nil {
		return x.MetadataSig
	}
	return nil
}

// HeartbeatV1 is a periodic liveness message carrying the sender's current HLC.
type HeartbeatV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoId                `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Hlc           *HLCTimestamp          `protobuf:"bytes,2,opt,name=hlc,proto3" json:"hlc,omitempty"`
	PeerId        string                 `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatV1) Reset() {
	*x = HeartbeatV1{}
	mi := &file_proto_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatV1) ProtoMessage() {}

func (x *HeartbeatV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatV1.ProtoReflect.Descriptor instead.
func (*HeartbeatV1) Descriptor() ([]byte, []int) {
	return file_proto_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatV1) GetRepo() *RepoId {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *HeartbeatV1) GetHlc() *HLCTimestamp {
	if x != nil {
		return x.Hlc
	}
	return nil
}

func (x *HeartbeatV1) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

// GossipMessage is the envelope published on the gossip topic.
type GossipMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GossipMessage_CommitAd
	//	*GossipMessage_Heartbeat
	Msg           isGossipMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_proto_gossip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_proto_gossip_proto_rawDescGZIP(), []int{3}
}

func (x *GossipMessage) GetMsg() isGossipMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GossipMessage) GetCommitAd() *CommitAdV1 {
	if x != nil {
		if x, ok := x.Msg.(*GossipMessage_CommitAd); ok {
			return x.CommitAd
		}
	}
	return nil
}

func (x *GossipMessage) GetHeartbeat() *HeartbeatV1 {
	if x != nil {
		if x, ok := x.Msg.(*GossipMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isGossipMessage_Msg interface {
	isGossipMessage_Msg()
}

type GossipMessage_CommitAd struct {
	CommitAd *CommitAdV1 `protobuf:"bytes,1,opt,name=commit_ad,json=commitAd,proto3,oneof"`
}

type GossipMessage_Heartbeat struct {
	Heartbeat *HeartbeatV1 `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*GossipMessage_CommitAd) isGossipMessage_Msg() {}

func (*GossipMessage_Heartbeat) isGossipMessage_Msg() {}

var File_proto_gossip_proto protoreflect.FileDescriptor

const file_proto_gossip_proto_rawDesc = "" +
	"\n" +
	"\x12proto/gossip.proto\x12\x05proto\x1a\x0fproto/hlc.proto\"7\n" +
	"\x06RepoId\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x1b\n" +
	"\trepo_name\x18\x02 \x01(\tR\brepoName\"\x9e\x01\n" +
	"\n" +
	"CommitAdV1\x12!\n" +
	"\x04repo\x18\x01 \x01(\v2\r.proto.RepoIdR\x04repo\x12%\n" +
	"\x03hlc\x18\x02 \x01(\v2\x13.proto.HLCTimestampR\x03hlc\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\fR\fmetadataJson\x12!\n" +
	"\fmetadata_sig\x18\x04 \x01(\fR\vmetadataSig\"p\n" +
	"\vHeartbeatV1\x12!\n" +
	"\x04repo\x18\x01 \x01(\v2\r.proto.RepoIdR\x04repo\x12%\n" +
	"\x03hlc\x18\x02 \x01(\v2\x13.proto.HLCTimestampR\x03hlc\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\tR\x06peerId\"|\n" +
	"\rGossipMessage\x120\n" +
	"\tcommit_ad\x18\x01 \x01(\v2\x11.proto.CommitAdV1H\x00R\bcommitAd\x122\n" +
	"\theartbeat\x18\x03 \x01(\v2\x12.proto.HeartbeatV1H\x00R\theartbeatB\x05\n" +
	"\x03msgB\tZ\a./protob\x06proto3"

var (
	file_proto_gossip_proto_rawDescOnce sync.Once
	file_proto_gossip_proto_rawDescData []byte
)

func file_proto_gossip_proto_rawDescGZIP() []byte {
	file_proto_gossip_proto_rawDescOnce.Do(func() {
		file_proto_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gossip_proto_rawDesc), len(file_proto_gossip_proto_rawDesc)))
	})
	return file_proto_gossip_proto_rawDescData
}

var file_proto_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_gossip_proto_goTypes = []any{
	(*RepoId)(nil),        // 0: proto.RepoId
	(*CommitAdV1)(nil),    // 1: proto.CommitAdV1
	(*HeartbeatV1)(nil),   // 2: proto.HeartbeatV1
	(*GossipMessage)(nil), // 3: proto.GossipMessage
	(*HLCTimestamp)(nil),  // 4: proto.HLCTimestamp
}
var file_proto_gossip_proto_depIdxs = []int32{
	0, // 0: proto.CommitAdV1.repo:type_name -> proto.RepoId
	4, // 1: proto.CommitAdV1.hlc:type_name -> proto.HLCTimestamp
	0, // 2: proto.HeartbeatV1.repo:type_name -> proto.RepoId
	4, // 3: proto.HeartbeatV1.hlc:type_name -> proto.HLCTimestamp
	1, // 4: proto.GossipMessage.commit_ad:type_name -> proto.CommitAdV1
	2, // 5: proto.GossipMessage.heartbeat:type_name -> proto.HeartbeatV1
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_gossip_proto_init() }
func file_proto_gossip_proto_init() {
	if File_proto_gossip_proto != nil {
		return
	}
	file_proto_hlc_proto_init()
	file_proto_gossip_proto_msgTypes[3].OneofWrappers = []any{
		(*GossipMessage_CommitAd)(nil),
		(*GossipMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gossip_proto_rawDesc), len(file_proto_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_gossip_proto_goTypes,
		DependencyIndexes: file_proto_gossip_proto_depIdxs,
		MessageInfos:      file_proto_gossip_proto_msgTypes,
	}.Build()
	File_proto_gossip_proto = out.File
	file_proto_gossip_proto_goTypes = nil
	file_proto_gossip_proto_depIdxs = nil
}
