// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/hlc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HLCTimestamp is the on-wire representation of doltswarm.HLCTimestamp.
type HLCTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wall          int64                  `protobuf:"varint,1,opt,name=wall,proto3" json:"wall,omitempty"`
	Logical       int32                  `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	PeerId        string                 `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HLCTimestamp) Reset() {
	*x = HLCTimestamp{}
	mi := &file_proto_hlc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HLCTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLCTimestamp) ProtoMessage() {}

func (x *HLCTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hlc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLCTimestamp.ProtoReflect.Descriptor instead.
func (*HLCTimestamp) Descriptor() ([]byte, []int) {
	return file_proto_hlc_proto_rawDescGZIP(), []int{0}
}

func (x *HLCTimestamp) GetWall() int64 {
	if x != nil {
		return x.Wall
	}
	return 0
}

func (x *HLCTimestamp) GetLogical() int32 {
	if x != nil {
		return x.Logical
	}
	return 0
}

func (x *HLCTimestamp) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

var File_proto_hlc_proto protoreflect.FileDescriptor

const file_proto_hlc_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/hlc.proto\x12\x05proto\"U\n" +
	"\fHLCTimestamp\x12\x12\n" +
	"\x04wall\x18\x01 \x01(\x03R\x04wall\x12\x18\n" +
	"\alogical\x18\x02 \x01(\x05R\alogical\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\tR\x06peerIdB\tZ\a./protob\x06proto3"

var (
	file_proto_hlc_proto_rawDescOnce sync.Once
	file_proto_hlc_proto_rawDescData []byte
)

func file_proto_hlc_proto_rawDescGZIP() []byte {
	file_proto_hlc_proto_rawDescOnce.Do(func() {
		file_proto_hlc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hlc_proto_rawDesc), len(file_proto_hlc_proto_rawDesc)))
	})
	return file_proto_hlc_proto_rawDescData
}

var file_proto_hlc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_hlc_proto_goTypes = []any{
	(*HLCTimestamp)(nil), // 0: proto.HLCTimestamp
}
var file_proto_hlc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_hlc_proto_init() }
func file_proto_hlc_proto_init() {
	if File_proto_hlc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hlc_proto_rawDesc), len(file_proto_hlc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_hlc_proto_goTypes,
		DependencyIndexes: file_proto_hlc_proto_depIdxs,
		MessageInfos:      file_proto_hlc_proto_msgTypes,
	}.Build()
	File_proto_hlc_proto = out.File
	file_proto_hlc_proto_goTypes = nil
	file_proto_hlc_proto_depIdxs = nil
}
