// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: tester.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecSQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statement     string                 `protobuf:"bytes,1,opt,name=statement,proto3" json:"statement,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSQLRequest) Reset() {
	*x = ExecSQLRequest{}
	mi := &file_tester_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSQLRequest) ProtoMessage() {}

func (x *ExecSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSQLRequest.ProtoReflect.Descriptor instead.
func (*ExecSQLRequest) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{0}
}

func (x *ExecSQLRequest) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *ExecSQLRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ExecSQLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commit        string                 `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSQLResponse) Reset() {
	*x = ExecSQLResponse{}
	mi := &file_tester_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSQLResponse) ProtoMessage() {}

func (x *ExecSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSQLResponse.ProtoReflect.Descriptor instead.
func (*ExecSQLResponse) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{1}
}

func (x *ExecSQLResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *ExecSQLResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecSQLResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type GetAllCommitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCommitsRequest) Reset() {
	*x = GetAllCommitsRequest{}
	mi := &file_tester_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCommitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCommitsRequest) ProtoMessage() {}

func (x *GetAllCommitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCommitsRequest.ProtoReflect.Descriptor instead.
func (*GetAllCommitsRequest) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{2}
}

type GetAllCommitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []string               `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCommitsResponse) Reset() {
	*x = GetAllCommitsResponse{}
	mi := &file_tester_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCommitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCommitsResponse) ProtoMessage() {}

func (x *GetAllCommitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCommitsResponse.ProtoReflect.Descriptor instead.
func (*GetAllCommitsResponse) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllCommitsResponse) GetCommits() []string {
	if x != nil {
		return x.Commits
	}
	return nil
}

type GetHeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeadRequest) Reset() {
	*x = GetHeadRequest{}
	mi := &file_tester_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadRequest) ProtoMessage() {}

func (x *GetHeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadRequest.ProtoReflect.Descriptor instead.
func (*GetHeadRequest) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{4}
}

type GetHeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commit        string                 `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeadResponse) Reset() {
	*x = GetHeadResponse{}
	mi := &file_tester_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadResponse) ProtoMessage() {}

func (x *GetHeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadResponse.ProtoReflect.Descriptor instead.
func (*GetHeadResponse) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{5}
}

func (x *GetHeadResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

type SetPeerLimitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Max           int32                  `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	Min           int32                  `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPeerLimitsRequest) Reset() {
	*x = SetPeerLimitsRequest{}
	mi := &file_tester_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPeerLimitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPeerLimitsRequest) ProtoMessage() {}

func (x *SetPeerLimitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPeerLimitsRequest.ProtoReflect.Descriptor instead.
func (*SetPeerLimitsRequest) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{6}
}

func (x *SetPeerLimitsRequest) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *SetPeerLimitsRequest) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

type SetPeerLimitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPeerLimitsResponse) Reset() {
	*x = SetPeerLimitsResponse{}
	mi := &file_tester_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPeerLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPeerLimitsResponse) ProtoMessage() {}

func (x *SetPeerLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPeerLimitsResponse.ProtoReflect.Descriptor instead.
func (*SetPeerLimitsResponse) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{7}
}

func (x *SetPeerLimitsResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type GetPeerCountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerCountsRequest) Reset() {
	*x = GetPeerCountsRequest{}
	mi := &file_tester_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerCountsRequest) ProtoMessage() {}

func (x *GetPeerCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerCountsRequest.ProtoReflect.Descriptor instead.
func (*GetPeerCountsRequest) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{8}
}

type GetPeerCountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPeers     int32                  `protobuf:"varint,1,opt,name=host_peers,json=hostPeers,proto3" json:"host_peers,omitempty"`
	GrpcPeers     int32                  `protobuf:"varint,2,opt,name=grpc_peers,json=grpcPeers,proto3" json:"grpc_peers,omitempty"`
	GossipPeers   int32                  `protobuf:"varint,3,opt,name=gossip_peers,json=gossipPeers,proto3" json:"gossip_peers,omitempty"`
	Err           string                 `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerCountsResponse) Reset() {
	*x = GetPeerCountsResponse{}
	mi := &file_tester_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerCountsResponse) ProtoMessage() {}

func (x *GetPeerCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tester_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerCountsResponse.ProtoReflect.Descriptor instead.
func (*GetPeerCountsResponse) Descriptor() ([]byte, []int) {
	return file_tester_proto_rawDescGZIP(), []int{9}
}

func (x *GetPeerCountsResponse) GetHostPeers() int32 {
	if x != nil {
		return x.HostPeers
	}
	return 0
}

func (x *GetPeerCountsResponse) GetGrpcPeers() int32 {
	if x != nil {
		return x.GrpcPeers
	}
	return 0
}

func (x *GetPeerCountsResponse) GetGossipPeers() int32 {
	if x != nil {
		return x.GossipPeers
	}
	return 0
}

func (x *GetPeerCountsResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_tester_proto protoreflect.FileDescriptor

const file_tester_proto_rawDesc = "" +
	"\n" +
	"\ftester.proto\x12\x05proto\"@\n" +
	"\x0eExecSQLRequest\x12\x1c\n" +
	"\tstatement\x18\x01 \x01(\tR\tstatement\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"S\n" +
	"\x0fExecSQLResponse\x12\x16\n" +
	"\x06commit\x18\x01 \x01(\tR\x06commit\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err\"\x16\n" +
	"\x14GetAllCommitsRequest\"1\n" +
	"\x15GetAllCommitsResponse\x12\x18\n" +
	"\acommits\x18\x01 \x03(\tR\acommits\"\x10\n" +
	"\x0eGetHeadRequest\")\n" +
	"\x0fGetHeadResponse\x12\x16\n" +
	"\x06commit\x18\x01 \x01(\tR\x06commit\":\n" +
	"\x14SetPeerLimitsRequest\x12\x10\n" +
	"\x03max\x18\x01 \x01(\x05R\x03max\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x05R\x03min\")\n" +
	"\x15SetPeerLimitsResponse\x12\x10\n" +
	"\x03err\x18\x01 \x01(\tR\x03err\"\x16\n" +
	"\x14GetPeerCountsRequest\"\x8a\x01\n" +
	"\x15GetPeerCountsResponse\x12\x1d\n" +
	"\n" +
	"host_peers\x18\x01 \x01(\x05R\thostPeers\x12\x1d\n" +
	"\n" +
	"grpc_peers\x18\x02 \x01(\x05R\tgrpcPeers\x12!\n" +
	"\fgossip_peers\x18\x03 \x01(\x05R\vgossipPeers\x12\x10\n" +
	"\x03err\x18\x04 \x01(\tR\x03err2\xea\x02\n" +
	"\x06Tester\x12:\n" +
	"\aExecSQL\x12\x15.proto.ExecSQLRequest\x1a\x16.proto.ExecSQLResponse\"\x00\x12L\n" +
	"\rGetAllCommits\x12\x1b.proto.GetAllCommitsRequest\x1a\x1c.proto.GetAllCommitsResponse\"\x00\x12:\n" +
	"\aGetHead\x12\x15.proto.GetHeadRequest\x1a\x16.proto.GetHeadResponse\"\x00\x12L\n" +
	"\rSetPeerLimits\x12\x1b.proto.SetPeerLimitsRequest\x1a\x1c.proto.SetPeerLimitsResponse\"\x00\x12L\n" +
	"\rGetPeerCounts\x12\x1b.proto.GetPeerCountsRequest\x1a\x1c.proto.GetPeerCountsResponse\"\x00B\tZ\a./protob\x06proto3"

var (
	file_tester_proto_rawDescOnce sync.Once
	file_tester_proto_rawDescData []byte
)

func file_tester_proto_rawDescGZIP() []byte {
	file_tester_proto_rawDescOnce.Do(func() {
		file_tester_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tester_proto_rawDesc), len(file_tester_proto_rawDesc)))
	})
	return file_tester_proto_rawDescData
}

var file_tester_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tester_proto_goTypes = []any{
	(*ExecSQLRequest)(nil),        // 0: proto.ExecSQLRequest
	(*ExecSQLResponse)(nil),       // 1: proto.ExecSQLResponse
	(*GetAllCommitsRequest)(nil),  // 2: proto.GetAllCommitsRequest
	(*GetAllCommitsResponse)(nil), // 3: proto.GetAllCommitsResponse
	(*GetHeadRequest)(nil),        // 4: proto.GetHeadRequest
	(*GetHeadResponse)(nil),       // 5: proto.GetHeadResponse
	(*SetPeerLimitsRequest)(nil),  // 6: proto.SetPeerLimitsRequest
	(*SetPeerLimitsResponse)(nil), // 7: proto.SetPeerLimitsResponse
	(*GetPeerCountsRequest)(nil),  // 8: proto.GetPeerCountsRequest
	(*GetPeerCountsResponse)(nil), // 9: proto.GetPeerCountsResponse
}
var file_tester_proto_depIdxs = []int32{
	0, // 0: proto.Tester.ExecSQL:input_type -> proto.ExecSQLRequest
	2, // 1: proto.Tester.GetAllCommits:input_type -> proto.GetAllCommitsRequest
	4, // 2: proto.Tester.GetHead:input_type -> proto.GetHeadRequest
	6, // 3: proto.Tester.SetPeerLimits:input_type -> proto.SetPeerLimitsRequest
	8, // 4: proto.Tester.GetPeerCounts:input_type -> proto.GetPeerCountsRequest
	1, // 5: proto.Tester.ExecSQL:output_type -> proto.ExecSQLResponse
	3, // 6: proto.Tester.GetAllCommits:output_type -> proto.GetAllCommitsResponse
	5, // 7: proto.Tester.GetHead:output_type -> proto.GetHeadResponse
	7, // 8: proto.Tester.SetPeerLimits:output_type -> proto.SetPeerLimitsResponse
	9, // 9: proto.Tester.GetPeerCounts:output_type -> proto.GetPeerCountsResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tester_proto_init() }
func file_tester_proto_init() {
	if File_tester_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tester_proto_rawDesc), len(file_tester_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tester_proto_goTypes,
		DependencyIndexes: file_tester_proto_depIdxs,
		MessageInfos:      file_tester_proto_msgTypes,
	}.Build()
	File_tester_proto = out.File
	file_tester_proto_goTypes = nil
	file_tester_proto_depIdxs = nil
}
