// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/tester.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tester_ExecSQL_FullMethodName       = "/proto.Tester/ExecSQL"
	Tester_GetAllCommits_FullMethodName = "/proto.Tester/GetAllCommits"
	Tester_GetHead_FullMethodName       = "/proto.Tester/GetHead"
)

// TesterClient is the client API for Tester service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TesterClient interface {
	ExecSQL(ctx context.Context, in *ExecSQLRequest, opts ...grpc.CallOption) (*ExecSQLResponse, error)
	GetAllCommits(ctx context.Context, in *GetAllCommitsRequest, opts ...grpc.CallOption) (*GetAllCommitsResponse, error)
	GetHead(ctx context.Context, in *GetHeadRequest, opts ...grpc.CallOption) (*GetHeadResponse, error)
}

type testerClient struct {
	cc grpc.ClientConnInterface
}

func NewTesterClient(cc grpc.ClientConnInterface) TesterClient {
	return &testerClient{cc}
}

func (c *testerClient) ExecSQL(ctx context.Context, in *ExecSQLRequest, opts ...grpc.CallOption) (*ExecSQLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecSQLResponse)
	err := c.cc.Invoke(ctx, Tester_ExecSQL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerClient) GetAllCommits(ctx context.Context, in *GetAllCommitsRequest, opts ...grpc.CallOption) (*GetAllCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllCommitsResponse)
	err := c.cc.Invoke(ctx, Tester_GetAllCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testerClient) GetHead(ctx context.Context, in *GetHeadRequest, opts ...grpc.CallOption) (*GetHeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHeadResponse)
	err := c.cc.Invoke(ctx, Tester_GetHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TesterServer is the server API for Tester service.
// All implementations should embed UnimplementedTesterServer
// for forward compatibility.
type TesterServer interface {
	ExecSQL(context.Context, *ExecSQLRequest) (*ExecSQLResponse, error)
	GetAllCommits(context.Context, *GetAllCommitsRequest) (*GetAllCommitsResponse, error)
	GetHead(context.Context, *GetHeadRequest) (*GetHeadResponse, error)
}

// UnimplementedTesterServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTesterServer struct{}

func (UnimplementedTesterServer) ExecSQL(context.Context, *ExecSQLRequest) (*ExecSQLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecSQL not implemented")
}
func (UnimplementedTesterServer) GetAllCommits(context.Context, *GetAllCommitsRequest) (*GetAllCommitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCommits not implemented")
}
func (UnimplementedTesterServer) GetHead(context.Context, *GetHeadRequest) (*GetHeadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHead not implemented")
}
func (UnimplementedTesterServer) testEmbeddedByValue() {}

// UnsafeTesterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TesterServer will
// result in compilation errors.
type UnsafeTesterServer interface {
	mustEmbedUnimplementedTesterServer()
}

func RegisterTesterServer(s grpc.ServiceRegistrar, srv TesterServer) {
	// If the following call pancis, it indicates UnimplementedTesterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tester_ServiceDesc, srv)
}

func _Tester_ExecSQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecSQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServer).ExecSQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tester_ExecSQL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServer).ExecSQL(ctx, req.(*ExecSQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tester_GetAllCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServer).GetAllCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tester_GetAllCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServer).GetAllCommits(ctx, req.(*GetAllCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tester_GetHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TesterServer).GetHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tester_GetHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TesterServer).GetHead(ctx, req.(*GetHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tester_ServiceDesc is the grpc.ServiceDesc for Tester service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tester_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Tester",
	HandlerType: (*TesterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecSQL",
			Handler:    _Tester_ExecSQL_Handler,
		},
		{
			MethodName: "GetAllCommits",
			Handler:    _Tester_GetAllCommits_Handler,
		},
		{
			MethodName: "GetHead",
			Handler:    _Tester_GetHead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tester.proto",
}
