// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/tester.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecSQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statement     string                 `protobuf:"bytes,1,opt,name=statement,proto3" json:"statement,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSQLRequest) Reset() {
	*x = ExecSQLRequest{}
	mi := &file_proto_tester_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSQLRequest) ProtoMessage() {}

func (x *ExecSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tester_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSQLRequest.ProtoReflect.Descriptor instead.
func (*ExecSQLRequest) Descriptor() ([]byte, []int) {
	return file_proto_tester_proto_rawDescGZIP(), []int{0}
}

func (x *ExecSQLRequest) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *ExecSQLRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ExecSQLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commit        string                 `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSQLResponse) Reset() {
	*x = ExecSQLResponse{}
	mi := &file_proto_tester_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSQLResponse) ProtoMessage() {}

func (x *ExecSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tester_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSQLResponse.ProtoReflect.Descriptor instead.
func (*ExecSQLResponse) Descriptor() ([]byte, []int) {
	return file_proto_tester_proto_rawDescGZIP(), []int{1}
}

func (x *ExecSQLResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *ExecSQLResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecSQLResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type GetAllCommitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCommitsRequest) Reset() {
	*x = GetAllCommitsRequest{}
	mi := &file_proto_tester_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCommitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCommitsRequest) ProtoMessage() {}

func (x *GetAllCommitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tester_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCommitsRequest.ProtoReflect.Descriptor instead.
func (*GetAllCommitsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tester_proto_rawDescGZIP(), []int{2}
}

type GetAllCommitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []string               `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCommitsResponse) Reset() {
	*x = GetAllCommitsResponse{}
	mi := &file_proto_tester_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCommitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCommitsResponse) ProtoMessage() {}

func (x *GetAllCommitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tester_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCommitsResponse.ProtoReflect.Descriptor instead.
func (*GetAllCommitsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tester_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllCommitsResponse) GetCommits() []string {
	if x != nil {
		return x.Commits
	}
	return nil
}

type GetHeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeadRequest) Reset() {
	*x = GetHeadRequest{}
	mi := &file_proto_tester_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadRequest) ProtoMessage() {}

func (x *GetHeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tester_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadRequest.ProtoReflect.Descriptor instead.
func (*GetHeadRequest) Descriptor() ([]byte, []int) {
	return file_proto_tester_proto_rawDescGZIP(), []int{4}
}

type GetHeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commit        string                 `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeadResponse) Reset() {
	*x = GetHeadResponse{}
	mi := &file_proto_tester_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadResponse) ProtoMessage() {}

func (x *GetHeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tester_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadResponse.ProtoReflect.Descriptor instead.
func (*GetHeadResponse) Descriptor() ([]byte, []int) {
	return file_proto_tester_proto_rawDescGZIP(), []int{5}
}

func (x *GetHeadResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

var File_proto_tester_proto protoreflect.FileDescriptor

const file_proto_tester_proto_rawDesc = "" +
	"\n" +
	"\x12proto/tester.proto\x12\x05proto\"@\n" +
	"\x0eExecSQLRequest\x12\x1c\n" +
	"\tstatement\x18\x01 \x01(\tR\tstatement\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"S\n" +
	"\x0fExecSQLResponse\x12\x16\n" +
	"\x06commit\x18\x01 \x01(\tR\x06commit\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err\"\x16\n" +
	"\x14GetAllCommitsRequest\"1\n" +
	"\x15GetAllCommitsResponse\x12\x18\n" +
	"\acommits\x18\x01 \x03(\tR\acommits\"\x10\n" +
	"\x0eGetHeadRequest\")\n" +
	"\x0fGetHeadResponse\x12\x16\n" +
	"\x06commit\x18\x01 \x01(\tR\x06commit2\xce\x01\n" +
	"\x06Tester\x12:\n" +
	"\aExecSQL\x12\x15.proto.ExecSQLRequest\x1a\x16.proto.ExecSQLResponse\"\x00\x12L\n" +
	"\rGetAllCommits\x12\x1b.proto.GetAllCommitsRequest\x1a\x1c.proto.GetAllCommitsResponse\"\x00\x12:\n" +
	"\aGetHead\x12\x15.proto.GetHeadRequest\x1a\x16.proto.GetHeadResponse\"\x00B\tZ\a./protob\x06proto3"

var (
	file_proto_tester_proto_rawDescOnce sync.Once
	file_proto_tester_proto_rawDescData []byte
)

func file_proto_tester_proto_rawDescGZIP() []byte {
	file_proto_tester_proto_rawDescOnce.Do(func() {
		file_proto_tester_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tester_proto_rawDesc), len(file_proto_tester_proto_rawDesc)))
	})
	return file_proto_tester_proto_rawDescData
}

var file_proto_tester_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_tester_proto_goTypes = []any{
	(*ExecSQLRequest)(nil),        // 0: proto.ExecSQLRequest
	(*ExecSQLResponse)(nil),       // 1: proto.ExecSQLResponse
	(*GetAllCommitsRequest)(nil),  // 2: proto.GetAllCommitsRequest
	(*GetAllCommitsResponse)(nil), // 3: proto.GetAllCommitsResponse
	(*GetHeadRequest)(nil),        // 4: proto.GetHeadRequest
	(*GetHeadResponse)(nil),       // 5: proto.GetHeadResponse
}
var file_proto_tester_proto_depIdxs = []int32{
	0, // 0: proto.Tester.ExecSQL:input_type -> proto.ExecSQLRequest
	2, // 1: proto.Tester.GetAllCommits:input_type -> proto.GetAllCommitsRequest
	4, // 2: proto.Tester.GetHead:input_type -> proto.GetHeadRequest
	1, // 3: proto.Tester.ExecSQL:output_type -> proto.ExecSQLResponse
	3, // 4: proto.Tester.GetAllCommits:output_type -> proto.GetAllCommitsResponse
	5, // 5: proto.Tester.GetHead:output_type -> proto.GetHeadResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tester_proto_init() }
func file_proto_tester_proto_init() {
	if File_proto_tester_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tester_proto_rawDesc), len(file_proto_tester_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tester_proto_goTypes,
		DependencyIndexes: file_proto_tester_proto_depIdxs,
		MessageInfos:      file_proto_tester_proto_msgTypes,
	}.Build()
	File_proto_tester_proto = out.File
	file_proto_tester_proto_goTypes = nil
	file_proto_tester_proto_depIdxs = nil
}
