// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/dbdownloader.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Downloader_DownloadFile_FullMethodName   = "/proto.Downloader/DownloadFile"
	Downloader_DownloadChunks_FullMethodName = "/proto.Downloader/DownloadChunks"
)

// DownloaderClient is the client API for Downloader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DownloaderClient interface {
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadFileResponse], error)
	DownloadChunks(ctx context.Context, in *DownloadChunksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadChunksResponse], error)
}

type downloaderClient struct {
	cc grpc.ClientConnInterface
}

func NewDownloaderClient(cc grpc.ClientConnInterface) DownloaderClient {
	return &downloaderClient{cc}
}

func (c *downloaderClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Downloader_ServiceDesc.Streams[0], Downloader_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadFileRequest, DownloadFileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Downloader_DownloadFileClient = grpc.ServerStreamingClient[DownloadFileResponse]

func (c *downloaderClient) DownloadChunks(ctx context.Context, in *DownloadChunksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadChunksResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Downloader_ServiceDesc.Streams[1], Downloader_DownloadChunks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadChunksRequest, DownloadChunksResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Downloader_DownloadChunksClient = grpc.ServerStreamingClient[DownloadChunksResponse]

// DownloaderServer is the server API for Downloader service.
// All implementations should embed UnimplementedDownloaderServer
// for forward compatibility.
type DownloaderServer interface {
	DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[DownloadFileResponse]) error
	DownloadChunks(*DownloadChunksRequest, grpc.ServerStreamingServer[DownloadChunksResponse]) error
}

// UnimplementedDownloaderServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDownloaderServer struct{}

func (UnimplementedDownloaderServer) DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[DownloadFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedDownloaderServer) DownloadChunks(*DownloadChunksRequest, grpc.ServerStreamingServer[DownloadChunksResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadChunks not implemented")
}
func (UnimplementedDownloaderServer) testEmbeddedByValue() {}

// UnsafeDownloaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DownloaderServer will
// result in compilation errors.
type UnsafeDownloaderServer interface {
	mustEmbedUnimplementedDownloaderServer()
}

func RegisterDownloaderServer(s grpc.ServiceRegistrar, srv DownloaderServer) {
	// If the following call pancis, it indicates UnimplementedDownloaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Downloader_ServiceDesc, srv)
}

func _Downloader_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DownloaderServer).DownloadFile(m, &grpc.GenericServerStream[DownloadFileRequest, DownloadFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Downloader_DownloadFileServer = grpc.ServerStreamingServer[DownloadFileResponse]

func _Downloader_DownloadChunks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadChunksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DownloaderServer).DownloadChunks(m, &grpc.GenericServerStream[DownloadChunksRequest, DownloadChunksResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Downloader_DownloadChunksServer = grpc.ServerStreamingServer[DownloadChunksResponse]

// Downloader_ServiceDesc is the grpc.ServiceDesc for Downloader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Downloader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Downloader",
	HandlerType: (*DownloaderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadFile",
			Handler:       _Downloader_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadChunks",
			Handler:       _Downloader_DownloadChunks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/dbdownloader.proto",
}
