// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proto/dbsyncer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HLC timestamp
type HLCTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wall          int64                  `protobuf:"varint,1,opt,name=wall,proto3" json:"wall,omitempty"`
	Logical       int32                  `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	PeerId        string                 `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HLCTimestamp) Reset() {
	*x = HLCTimestamp{}
	mi := &file_proto_dbsyncer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HLCTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLCTimestamp) ProtoMessage() {}

func (x *HLCTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbsyncer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLCTimestamp.ProtoReflect.Descriptor instead.
func (*HLCTimestamp) Descriptor() ([]byte, []int) {
	return file_proto_dbsyncer_proto_rawDescGZIP(), []int{0}
}

func (x *HLCTimestamp) GetWall() int64 {
	if x != nil {
		return x.Wall
	}
	return 0
}

func (x *HLCTimestamp) GetLogical() int32 {
	if x != nil {
		return x.Logical
	}
	return 0
}

func (x *HLCTimestamp) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

// Commit advertisement with HLC identity
type AdvertiseCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Hlc           *HLCTimestamp          `protobuf:"bytes,2,opt,name=hlc,proto3" json:"hlc,omitempty"`
	ContentHash   string                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	CommitHash    string                 `protobuf:"bytes,4,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"` // Hash on sender's main
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Author        string                 `protobuf:"bytes,6,opt,name=author,proto3" json:"author,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=date,proto3" json:"date,omitempty"`
	Signature     string                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"` // Signature over metadata (authoritative)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertiseCommitRequest) Reset() {
	*x = AdvertiseCommitRequest{}
	mi := &file_proto_dbsyncer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertiseCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertiseCommitRequest) ProtoMessage() {}

func (x *AdvertiseCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbsyncer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertiseCommitRequest.ProtoReflect.Descriptor instead.
func (*AdvertiseCommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_dbsyncer_proto_rawDescGZIP(), []int{1}
}

func (x *AdvertiseCommitRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *AdvertiseCommitRequest) GetHlc() *HLCTimestamp {
	if x != nil {
		return x.Hlc
	}
	return nil
}

func (x *AdvertiseCommitRequest) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *AdvertiseCommitRequest) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *AdvertiseCommitRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdvertiseCommitRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AdvertiseCommitRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdvertiseCommitRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *AdvertiseCommitRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type AdvertiseCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertiseCommitResponse) Reset() {
	*x = AdvertiseCommitResponse{}
	mi := &file_proto_dbsyncer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertiseCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertiseCommitResponse) ProtoMessage() {}

func (x *AdvertiseCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbsyncer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertiseCommitResponse.ProtoReflect.Descriptor instead.
func (*AdvertiseCommitResponse) Descriptor() ([]byte, []int) {
	return file_proto_dbsyncer_proto_rawDescGZIP(), []int{2}
}

func (x *AdvertiseCommitResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// Request commits since a given HLC (for missing ads recovery)
type RequestCommitsSinceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceHlc      *HLCTimestamp          `protobuf:"bytes,1,opt,name=since_hlc,json=sinceHlc,proto3" json:"since_hlc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCommitsSinceRequest) Reset() {
	*x = RequestCommitsSinceRequest{}
	mi := &file_proto_dbsyncer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCommitsSinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCommitsSinceRequest) ProtoMessage() {}

func (x *RequestCommitsSinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbsyncer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCommitsSinceRequest.ProtoReflect.Descriptor instead.
func (*RequestCommitsSinceRequest) Descriptor() ([]byte, []int) {
	return file_proto_dbsyncer_proto_rawDescGZIP(), []int{3}
}

func (x *RequestCommitsSinceRequest) GetSinceHlc() *HLCTimestamp {
	if x != nil {
		return x.SinceHlc
	}
	return nil
}

type RequestCommitsSinceResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Commits       []*AdvertiseCommitRequest `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCommitsSinceResponse) Reset() {
	*x = RequestCommitsSinceResponse{}
	mi := &file_proto_dbsyncer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCommitsSinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCommitsSinceResponse) ProtoMessage() {}

func (x *RequestCommitsSinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbsyncer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCommitsSinceResponse.ProtoReflect.Descriptor instead.
func (*RequestCommitsSinceResponse) Descriptor() ([]byte, []int) {
	return file_proto_dbsyncer_proto_rawDescGZIP(), []int{4}
}

func (x *RequestCommitsSinceResponse) GetCommits() []*AdvertiseCommitRequest {
	if x != nil {
		return x.Commits
	}
	return nil
}

var File_proto_dbsyncer_proto protoreflect.FileDescriptor

const file_proto_dbsyncer_proto_rawDesc = "" +
	"\n" +
	"\x14proto/dbsyncer.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n" +
	"\fHLCTimestamp\x12\x12\n" +
	"\x04wall\x18\x01 \x01(\x03R\x04wall\x12\x18\n" +
	"\alogical\x18\x02 \x01(\x05R\alogical\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\tR\x06peerId\"\xb2\x02\n" +
	"\x16AdvertiseCommitRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12%\n" +
	"\x03hlc\x18\x02 \x01(\v2\x13.proto.HLCTimestampR\x03hlc\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\x12\x1f\n" +
	"\vcommit_hash\x18\x04 \x01(\tR\n" +
	"commitHash\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06author\x18\x06 \x01(\tR\x06author\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12.\n" +
	"\x04date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x1c\n" +
	"\tsignature\x18\t \x01(\tR\tsignature\"5\n" +
	"\x17AdvertiseCommitResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"N\n" +
	"\x1aRequestCommitsSinceRequest\x120\n" +
	"\tsince_hlc\x18\x01 \x01(\v2\x13.proto.HLCTimestampR\bsinceHlc\"V\n" +
	"\x1bRequestCommitsSinceResponse\x127\n" +
	"\acommits\x18\x01 \x03(\v2\x1d.proto.AdvertiseCommitRequestR\acommits2\xbe\x01\n" +
	"\bDBSyncer\x12R\n" +
	"\x0fAdvertiseCommit\x12\x1d.proto.AdvertiseCommitRequest\x1a\x1e.proto.AdvertiseCommitResponse\"\x00\x12^\n" +
	"\x13RequestCommitsSince\x12!.proto.RequestCommitsSinceRequest\x1a\".proto.RequestCommitsSinceResponse\"\x00B-Z+github.com/nustiueudinastea/doltswarm/protob\x06proto3"

var (
	file_proto_dbsyncer_proto_rawDescOnce sync.Once
	file_proto_dbsyncer_proto_rawDescData []byte
)

func file_proto_dbsyncer_proto_rawDescGZIP() []byte {
	file_proto_dbsyncer_proto_rawDescOnce.Do(func() {
		file_proto_dbsyncer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dbsyncer_proto_rawDesc), len(file_proto_dbsyncer_proto_rawDesc)))
	})
	return file_proto_dbsyncer_proto_rawDescData
}

var file_proto_dbsyncer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_dbsyncer_proto_goTypes = []any{
	(*HLCTimestamp)(nil),                // 0: proto.HLCTimestamp
	(*AdvertiseCommitRequest)(nil),      // 1: proto.AdvertiseCommitRequest
	(*AdvertiseCommitResponse)(nil),     // 2: proto.AdvertiseCommitResponse
	(*RequestCommitsSinceRequest)(nil),  // 3: proto.RequestCommitsSinceRequest
	(*RequestCommitsSinceResponse)(nil), // 4: proto.RequestCommitsSinceResponse
	(*timestamppb.Timestamp)(nil),       // 5: google.protobuf.Timestamp
}
var file_proto_dbsyncer_proto_depIdxs = []int32{
	0, // 0: proto.AdvertiseCommitRequest.hlc:type_name -> proto.HLCTimestamp
	5, // 1: proto.AdvertiseCommitRequest.date:type_name -> google.protobuf.Timestamp
	0, // 2: proto.RequestCommitsSinceRequest.since_hlc:type_name -> proto.HLCTimestamp
	1, // 3: proto.RequestCommitsSinceResponse.commits:type_name -> proto.AdvertiseCommitRequest
	1, // 4: proto.DBSyncer.AdvertiseCommit:input_type -> proto.AdvertiseCommitRequest
	3, // 5: proto.DBSyncer.RequestCommitsSince:input_type -> proto.RequestCommitsSinceRequest
	2, // 6: proto.DBSyncer.AdvertiseCommit:output_type -> proto.AdvertiseCommitResponse
	4, // 7: proto.DBSyncer.RequestCommitsSince:output_type -> proto.RequestCommitsSinceResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_dbsyncer_proto_init() }
func file_proto_dbsyncer_proto_init() {
	if File_proto_dbsyncer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dbsyncer_proto_rawDesc), len(file_proto_dbsyncer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dbsyncer_proto_goTypes,
		DependencyIndexes: file_proto_dbsyncer_proto_depIdxs,
		MessageInfos:      file_proto_dbsyncer_proto_msgTypes,
	}.Build()
	File_proto_dbsyncer_proto = out.File
	file_proto_dbsyncer_proto_goTypes = nil
	file_proto_dbsyncer_proto_depIdxs = nil
}
