version: '3'

vars:
  CGO_FLAGS: 'CGO_LDFLAGS="-L/opt/homebrew/opt/icu4c@78/lib" CGO_CPPFLAGS="-I/opt/homebrew/opt/icu4c@78/include" CGO_CFLAGS="-I/opt/homebrew/opt/icu4c@78/include"'
  GO_ENV: 'GONOSUMDB=github.com/nustiueudinastea/*'
  DOCKER_IMAGE: doltswarmdemo
  NR_INSTANCES: '{{.NR_INSTANCES | default "5"}}'

tasks:
  build:
    desc: Build the ddolt binary
    cmds:
      - '{{.GO_ENV}} {{.CGO_FLAGS}} go build -o ddolt .'

  test:
    desc: Run all tests locally
    vars:
      TIMEOUT: '{{.TIMEOUT | default "30m"}}'
    cmds:
      - '{{.GO_ENV}} {{.CGO_FLAGS}} NR_INSTANCES={{.NR_INSTANCES}} go test -v -timeout {{.TIMEOUT}} ./...'

  test:integration:
    desc: Run only the integration test
    cmds:
      - '{{.GO_ENV}} {{.CGO_FLAGS}} NR_INSTANCES={{.NR_INSTANCES}} ENABLE_INIT_PROCESS_OUTPUT=true go test -v -timeout 10m -run TestIntegration'

  test:sequential:
    desc: Run sequential writes propagation test
    cmds:
      - '{{.GO_ENV}} {{.CGO_FLAGS}} NR_INSTANCES={{.NR_INSTANCES}} go test -v -timeout 10m -run TestSequentialWritesPropagation'

  test:concurrent:
    desc: Run concurrent writes test
    cmds:
      - '{{.GO_ENV}} {{.CGO_FLAGS}} NR_INSTANCES={{.NR_INSTANCES}} go test -v -timeout 10m -run TestConcurrentWrites'

  test:order:
    desc: Run commit order consistency test
    cmds:
      - '{{.GO_ENV}} {{.CGO_FLAGS}} NR_INSTANCES={{.NR_INSTANCES}} go test -v -timeout 10m -run TestCommitOrderConsistency'

  docker:build:
    desc: Build Docker image (includes doltswarm library)
    cmds:
      - ./docker/build-docker.sh

  docker:test:containers:
    desc: Run tests with each peer in a Docker container (build image first with docker:build)
    cmds:
      - '{{.GO_ENV}} {{.CGO_FLAGS}} NR_INSTANCES={{.NR_INSTANCES}} go test -tags docker -v -timeout 15m -run TestDockerIntegration'

  docker:test:
    desc: Build Docker image and run integration test
    cmds:
      - ./docker/build-docker.sh
      - '{{.GO_ENV}} {{.CGO_FLAGS}} NR_INSTANCES={{.NR_INSTANCES}} go test -tags docker -v -timeout 15m -run TestDockerIntegration'

  docker:test:concurrent:
    desc: Run concurrent writes test with Docker containers (build image first with docker:build)
    cmds:
      - '{{.GO_ENV}} {{.CGO_FLAGS}} NR_INSTANCES={{.NR_INSTANCES}} go test -tags docker -v -timeout 15m -run TestDockerConcurrentWrites'

  docker:shell:
    desc: Open a shell in the Docker container
    cmds:
      - docker run --rm -it {{.DOCKER_IMAGE}} /bin/bash

  docker:clean:
    desc: Clean up Docker test containers and networks
    cmds:
      - docker ps -a --filter "label=doltswarmdemo-test" -q | xargs -r docker rm -f || true
      - docker network rm doltswarmdemo-test || true
      - docker images --filter "reference=doltswarmdemo-initialized*" -q | xargs -r docker rmi -f || true

  clean:
    desc: Clean up test artifacts and processes
    cmds:
      - pkill -9 -f ddolt || true
      - rm -rf temp/tst* || true
      - rm -f ddolt || true

  kill:
    desc: Kill all running ddolt processes
    cmds:
      - pkill -9 -f ddolt || true

  default:
    desc: Show available tasks
    cmds:
      - task --list
