x-node:
  &default-node
  image: jepsen-node:dev1
  tty: true
  tmpfs:
    - /run:size=100M
    - /run/lock:size=100M
  cgroup: host
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    - "jepsen-shared:/var/jepsen/shared"
  networks:
    - jepsen
  cap_add:
    - ALL
  ports:
    - ${JEPSEN_PORT:-22}
  stop_signal: SIGRTMIN+3
  healthcheck:
    test: [ 'CMD-SHELL', 'systemctl status sshd | grep "Active: active (running)"' ]
    interval: 1s
    timeout: 1s
    retries: 3
    start_period: 3s
  depends_on: 
    setup:
      condition: service_completed_successfully

volumes:
  jepsen-shared:

networks:
  jepsen:

services:
  setup:
    image: jgoerzen/debian-base-standard:bullseye
    container_name: jepsen-setup
    hostname: setup
    volumes:
      - "jepsen-shared:/var/jepsen/shared"
    entrypoint: [ 'rm', '-rf', '/var/jepsen/shared/nodes' ] 
  control:
    image: jepsen-control:dev1
    container_name: jepsen-control
    hostname: control
    depends_on:
      n1:
        condition: service_healthy
      n2:
        condition: service_healthy
      n3:
        condition: service_healthy
      n4:
        condition: service_healthy
      n5:
        condition: service_healthy

    ports:
      - "22"
      - "8080"
    networks:
      - jepsen
    volumes:
      - "jepsen-shared:/var/jepsen/shared"
    stop_signal: SIGRTMIN+3
  n1:
    << : *default-node
    container_name: jepsen-n1
    hostname: n1
  n2:
    << : *default-node
    container_name: jepsen-n2
    hostname: n2
  n3:
    << : *default-node
    container_name: jepsen-n3
    hostname: n3
  n4:
    << : *default-node
    container_name: jepsen-n4
    hostname: n4
  n5:
    << : *default-node
    container_name: jepsen-n5
    hostname: n5

